# Generated by Django 2.1.3 on 2018-11-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('dob', models.DateField()),
            ],
        ),
    ]
