# Generated by Django 2.1.3 on 2018-11-15 01:57

from django.db import migrations, models
import django.db.models.deletion
import utils.file_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('dob', models.DateTimeField()),
                ('phone', models.CharField(max_length=16)),
                ('cell', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(height_field='thumbnail_height', upload_to=utils.file_utils.get_image_file_path, width_field='thumbnail_width')),
                ('medium', models.ImageField(height_field='medium_height', upload_to=utils.file_utils.get_image_file_path, width_field='medium_width')),
                ('large', models.ImageField(height_field='large_height', upload_to=utils.file_utils.get_image_file_path, width_field='large_width')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='employee.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='employee.Employee'),
        ),
    ]
