# Generated by Django 2.1.3 on 2018-11-15 16:40

from django.db import migrations, models
import utils.file_utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large',
            field=models.ImageField(upload_to=utils.file_utils.get_image_file_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium',
            field=models.ImageField(upload_to=utils.file_utils.get_image_file_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(upload_to=utils.file_utils.get_image_file_path),
        ),
    ]
