# Generated by Django 2.1.3 on 2018-11-16 21:04

from django.db import migrations, models
import utils.file_utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20181115_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cell',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='large',
            field=models.ImageField(default='', upload_to=utils.file_utils.get_image_file_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium',
            field=models.ImageField(default='', upload_to=utils.file_utils.get_image_file_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=utils.file_utils.get_image_file_path),
        ),
    ]
