# Generated by Django 2.1.3 on 2018-11-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20181116_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.CharField(max_length=128),
        ),
    ]
